trigger:
  branches:
    include:
    - main
    - develop
variables:
- group: Polaris_var
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: BlackDuckSecurityScan@2
      displayName: 'Polaris Scan'
      inputs:
        polaris_server_url: $(POLARIS_SERVERURL)
        polaris_access_token: $(POLARIS_ACCESSTOKEN)
        polaris_assessment_types: 'SAST'
        polaris_application_name: Mirul_test123
        polaris_project_name: test_project
        polaris.onboarding: true
        include_diagnostics: false
        mark_build_status: 'SucceededWithIssues'